'com.internet.browser.secure': 'CT=1;NM=Internet Browser;ST=1;TP=browser'
'net.samay.grammar': 'CT=5;English Grammar Quiz;ST=0;TP=app'
'earn.bchfaucet': 'CT=2;Earn BCH Faucet;ST=1;TP=app'
'com.preff.kb.xm.gp': 'CT=4;Emoji Keyboard;ST=1;TP=app'
'com.infinity.sotatheme': 'CT=3;Solitaire Theme - Classic Poker;ST=1;TP=app'
'com.shepeliok.driving.race.lcruiser': 'CT=3;City SUV Toyota Land Cruiser 200 Parking;ST=1;TP=app'
'com.krasiviyprojector.trikota': 'CT=6;11K Illumination Graphics;ST=1;TP=app'
'com.free.full.movie.downloader.hollywoodbollywood.hindidubbed.allmoviedownloader': 'CT=7;Download movies video HD;ST=1;TP=app'
'com.Palmier.bt': 'CT=4;Cute BT21 HD Wallpaper;ST=1;TP=app'
'dev.rokitskiy.gts_watchface': 'CT=4;Watch faces for Amazfit GTS;ST=1;TP=app'
'com.my.newproject10': 'CT=4;Smart stop watch;ST=0;TP=app'