# NM = name app
# CT = category id
# ST = store in play market
# TP = type app

# BD = bad app: scram or patched app

# Browsers

'acr.browser.Hexa': 'CT=1;NM=Hexa Web Browser;ST=0;TP=browser;'
'acr.browser.raisebrowserfull': 'CT=1;NM=Raise Fast & Safe Browser;ST=1;TP=browser;'
'acr.tez.browse': 'CT=1;NM=Browspeed - SuperFast Browser;ST=0;TP=browser;'
'com.Fast.BrowserUc.lite': 'CT=1;NM=Fast Browser UC 2022;ST=1;TP=browser'
'com.UCMobile.intl': 'CT=1;NM=UC Browser-Safe, Fast, Private;ST=1;TP=browser;'
'com.aloha.browser': 'CT=1;NM=Aloha Browser;ST=1;TP=browser;'
'com.browser.indian.fast': 'CT=1;NM=Indian Browser;ST=1;TP=browser;'
'com.cake.browser': 'CT=1;NM=Cake Web Browser;ST=1;TP=browser;'
'com.iebrowser.fast': 'CT=1;NM=IE Browser Fast;ST=1;TP=browser'
'com.inco.browser': 'CT=1;NM=Inco Private Browser;ST=1;TP=browser;'
'com.incognit.bowser': 'CT=1;NM=Private Browser (JkSense);ST=1;TP=browser;'
'com.insta.browser': 'CT=1;NM=Insta Browser;ST=0;TP=browser;'
'com.internet.browser.secure': 'CT=1;NM=Internet Browser;ST=1;TP=browser'
'com.mi.globalbrowser.mini': 'CT=1;NM=Mint Browser;ST=1;TP=browser;'
'com.microsoft.emmx.beta': 'CT=1;NM=Microsoft Edge Beta;ST=1;TP=browser;'
'com.mx.browser': 'CT=1;NM=Maxthon Browser;ST=1;TP=browser;'
'com.mycompany.app.soulbrowser': 'CT=1;NM=Soul Browser;ST=1;TP=browser;'
'com.oh.bro': 'CT=1;NM=OH Web Browser;ST=1;TP=browser;'
'com.opera.mini.native.beta15pahlevan': 'CT=1;NM=Opera Mini;ST=0;TP=browser;BD=1'
'com.ucold.browser.secure.browse': 'CT=1;NM=Uc Mini - Private Browser;ST=1;TP=browser'
'com.vivaldi.browser.snapshot': 'CT=1;NM=Vivaldi Browser Snapshot;ST=1;TP=browser;'
'com.wSilverMobBrowser': 'CT=1;NM=SilverMob US Browser;ST=0;TP=browser;'
'fast.explorer.web.browser': 'CT=1;NM=Web Browser & Fast Explorer;ST=1;TP=browser;'
'mark.via.gp': 'CT=1;NM=Via;ST=1;TP=browser;'
'net.onecook.browser': 'CT=1;NM=Stargon Browser;ST=1;TP=browser;'
'org.mini.freebrowser': 'CT=1;NM=CM Browser Mini;ST=0;TP=browser;'
'org.mozilla.klar': 'CT=1;NM=Firefox Klar;ST=1;TP=browser;'
'org.mozilla.rocket': 'CT=1;NM=Firefox Lite;ST=0;TP=browser;'
'org.torproject.torbrowser': 'CT=1;NM=Tor Browser;ST=1;TP=browser;'
'phx.hot.browser': 'CT=1;NM=Anka Browser;ST=1;TP=browser;'
'web.browser.dragon': 'CT=1;NM=Dragon Browser;ST=1;TP=browser;'
'com.my.browser2021': 'CT=1;NM=Browser 2021;ST=0;TP=browser;'
'quick.browser.secure': 'CT=1;NM=Quick Browser;ST=1;TP=browser;'
'com.quickbig.browser': 'CT=1;NM=Uc Mini Indian Browser;ST=1;TP=browser;'

# Vpn Browsers

'acr.browser.linxy': 'CT=1;NM=Vegas Browser;ST=1;TP=browser;'
'org.torproject.android': 'CT=1;NM=Orbot;ST=1;TP=browser;'
'com.nesc.adblockplusvpn': 'CT=1;NM=Proxy Surf - Buka Blokir Web Tanpa VPN;ST=1;TP=browser;'
'com.nesc.proxybrowser': 'CT=1;NM=Proxy Browser - Buka Blokir Situs Web;ST=1;TP=browser;'
'com.nordvpn.android': 'CT=1;NM=Nord VPN;ST=0;TP=app;'
'com.pandavpn.androidproxy': 'CT=1;NM=Panda VPN Pro;ST=0;TP=app;'

# Apps

'com.panda.likerro': 'CT=10;NM=Likerro;ST=1;TP=app'
'com.pandrama.app': 'CT=11;NM=Pandrama Dramas en español;ST=0;TP=app'
'com.yandex.yamb': 'CT=9;NM=Yandex.Messenger;ST=0;TP=app'
'com.sgiggle.production': 'CT=9;NM=Tango-Live Stream & Video Chat;ST=0;TP=app'
'info.sunista.app': 'CT=8;NM=Sanista - Persian Instagram;ST=0;TP=app'
'com.instapro.app': 'CT=8;NM=InstaPro;ST=0;TP=app'
'net.samay.grammar': 'CT=5;English Grammar Quiz;ST=0;TP=app'
'com.mybrowser.dlvdappfree': 'CT=1;Download Video;ST=1;TP=app'
'com.mybrowserapp.downloadvideobrowserfree': 'CT=1;Download Video Fast;ST=1;TP=app'