name: Run EsLint

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  es-lint:
    name: EsLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          args: './index.d.ts --max-warnings 0'
